#Temporary file paths
INPUT_TEMPFILE_PATH = "temp/source.txt"
OUTPUT_TEMPFILE_PATH = "temp/result.txt"

#Statement tags
BLOCK_START_TAG = "code-block-start"
BLOCK_END_TAG = "code-block-end"
CONDITIONAL_TAG = "conditional"
DECLARATION_TAG = "variable-declaration"
FUNCTION_TAG = "function-declaration"
FUNCTION_DEFINITION_TAG = "function-definition"
INITIATION_TAG = "variable-initiation"
INPUT_TAG = "input"
LOOP_TAG = "loop"
MULTI_COMMENT_TAG = "multi-line-comment"
OUTPUT_TAG = "output"
PREPROCESSOR_TAG = "include-library"
RETURN_TAG = "return-statement"
SINGLE_COMMENT_TAG = "single-line-comment"
UNKNOWN_TAG = "unknown"