#Temporary file paths

INPUT_TEMPFILE_PATH = "temp/source.txt"
OUTPUT_TEMPFILE_PATH = "temp/result.txt"

#Statement tags
BLOCK_START_TAG = "code-block-start"
BLOCK_END_TAG = "code-block-end"
BREAK_TAG = "break-statement"
CASE_TAG = "switch-case-statement"
CONDITIONAL_TAG = "conditional"
CONTINUE_TAG = "continue-statement"
DECLARATION_TAG = "variable-declaration"
DECREMENT_INCREMENT_TAG = "decrement/increment"
DEFINE_TAG = "define-preprocessor"
FUNCTION_CALL_TAG = "function-call"
FUNCTION_DEFINITION_TAG = "function-definition"
FUNCTION_TAG = "function-declaration"
INITIATION_TAG = "variable-initiation"
INPUT_TAG = "input"
LOOP_TAG = "loop"
MULTI_COMMENT_TAG = "multi-line-comment"
OUTPUT_TAG = "output"
PREPROCESSOR_TAG = "include-library"
RETURN_TAG = "return-statement"
SEED_TAG = "random-seed"
SINGLE_COMMENT_TAG = "single-line-comment"
SWITCH_TAG = "switch-conditional"
UNKNOWN_TAG = "unknown"
